#!/bin/bash
#SBATCH --partition=DGX
##SBATCH --nodelist=dgx001
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=6:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32           
#SBATCH --mem=400G                
#SBATCH --job-name=test
#SBATCH --gres=gpu:5


#source /etc/profile.d/modules.sh
#module use /opt/nvidia/hpc_sdk/modulefiles/
#module load nvhpc

source /u/area/ddoimo/anaconda3/bin/activate ./env_amd

#source /u/area/ddoimo/anaconda3/bin/activate /u/area/ddoimo/ddoimo/open/open-instruct/env_amd

export OMP_NUM_THREADS=32

#export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"

#export CUDA_LAUNCH_BLOCKING=1

model_name=llama-3-70b
path=llama_v3

#model_name=mistral-1-7b
#path=mistral_v1

torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:0 \
       	--nnodes=1  --nproc-per-node=5 \
    diego/extraction/extract_repr.py \
    --dataset "mmlu" \
    --checkpoint_dir  "/u/area/ddoimo/ddoimo/models/$path/models_hf/$model_name" \
    --use_slow_tokenizer \
    --preprocessing_num_workers 16 \
    --micro_batch_size 1 \
    --out_dir "./results" \
    --logging_steps 100 \
    --layer_interval 1 \
    --remove_duplicates \
    --use_last_token \
    --max_seq_len 4090 \
    --num_few_shots 0 \
    --save_distances --save_repr \
    --measure_ari \
    --finetuned_path  "/u/area/ddoimo/ddoimo/finetuning_llm/open-instruct/results" \
    --finetuned_mode "dev_val_balanced_40samples" \
    --finetuned_epochs 4 \
    --model_seed 0 \
    --step $step \
    --split "dev+validation" \
    --dataset_path "/orfeo/cephfs/scratch/area/ddoimo/open/geometric_lens/repo/diego/science_qa" \
    #--prompt_mmlu \
    #--ckpt_epoch 4 \
    #--few_shot_topics 
    #--step $step
    #--sample_same_questions \
    #--indices_path "diego/sorted_indices_subjects/${num_shots}shot/sorted_indices_$seed.pkl"\
    #--measure_ari 
    
    #--ckpt_epoch 4  
    #--split "test" \
    #--prompt_search
    #--random_order \
    #--skip_choices 
    #--wrong_answers  
    #--declarative 
    #--random_subject
    #--declarative
    #--sample_questions
    #--declarative \
    #--aux_few_shot 
    #--prompt_search \
    #--aux_few_shot  
    #--sample_questions
    # --finetuned_path  "/u/area/ddoimo/ddoimo/finetuning_llm/open-instruct/results" \
    # --finetuned_mode "test_balanced" \
    # --finetuned_epochs 4 \
    # --ckpt_epoch 3 
