#!/bin/bash
#SBATCH --partition=DGX
##SBATCH --nodelist=dgx001
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=4:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=32           
#SBATCH --mem=120G                
#SBATCH --job-name=test
#SBATCH --gres=gpu:0


#source /etc/profile.d/modules.sh
#module use /opt/nvidia/hpc_sdk/modulefiles/
#module load nvhpc

source /u/area/ddoimo/anaconda3/bin/activate ./env_amd

#source /u/area/ddoimo/anaconda3/bin/activate /u/area/ddoimo/ddoimo/open/open-instruct/env_amd

export OMP_NUM_THREADS=32

export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"


python diego/analysis/repr_comparison.py \
    --model "llama-3-8b" \
    --finetuned_mode "test_balanced" \
    --results_path "diego/analysis/results" \
    --epochs 4 \
    --eval_dataset "test" \
    --num_shots 5
