_CACHE_DIR = "/home/alexserra98/helm-suite/MCQA_Benchmark/output_test_result"
_OUTPUT_DIR ="/home/alexserra98/helm-suite/MCQA_Benchmark/output_test_result" 
_OUTPUT_RESULT_DIR = "/home/alexserra98/helm-suite/MCQA_Benchmark/"
# _CACHE_DIR = "/orfeo/scratch/dssc/zenocosini"
# _OUTPUT_DIR = "/orfeo/scratch/dssc/zenocosini"
# _OUTPUT_RESULT_DIR = "/orfeo/scratch/dssc/zenocosini"
